# Generated by Django 6.0.6 on 2026-06-08 08:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('role_permissions', models.JSONField(blank=True, default=dict)),
                ('available_roles', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('months', models.IntegerField(default=1)),
                ('student_limit', models.PositiveIntegerField(default=0)),
                ('discount_enabled', models.BooleanField(default=False)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_badge', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_active_students', models.BooleanField(default=True)),
                ('include_trial_students', models.BooleanField(default=True)),
                ('include_archived_students', models.BooleanField(default=False)),
                ('include_frozen_students', models.BooleanField(default=False)),
                ('include_deleted_students', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setting', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('session_string', models.TextField(blank=True, null=True)),
                ('interval_hours', models.IntegerField(choices=[(6, '6 Hours'), (12, '12 Hours'), (24, '24 Hours')], default=24)),
                ('is_active', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_setting', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('hide_logo', models.BooleanField(default=False)),
                ('hide_text_field', models.BooleanField(default=False)),
                ('hide_receipt_number', models.BooleanField(default=False)),
                ('hide_organization_name', models.BooleanField(default=False)),
                ('hide_student_name', models.BooleanField(default=False)),
                ('hide_phone_number', models.BooleanField(default=False)),
                ('hide_balance', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_setting', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ignore_trial_salary', models.BooleanField(default=True)),
                ('ignore_archived_salary', models.BooleanField(default=True)),
                ('include_discount_salary', models.BooleanField(default=True)),
                ('salary_with_discount', models.BooleanField(default=True)),
                ('salary_for_archived', models.BooleanField(default=False)),
                ('link_salary_attendance', models.BooleanField(default=False)),
                ('salary_only_teacher_marks', models.BooleanField(default=False)),
                ('salary_only_attended', models.BooleanField(default=False)),
                ('salary_trial_students', models.BooleanField(default=False)),
                ('salary_frozen_students', models.BooleanField(default=False)),
                ('allow_teacher_sms', models.BooleanField(default=True)),
                ('hide_student_data', models.BooleanField(default=False)),
                ('attendance_during_lesson', models.BooleanField(default=False)),
                ('allow_group_overlap', models.BooleanField(default=False)),
                ('show_group_balance', models.BooleanField(default=True)),
                ('uzum_settings', models.CharField(blank=True, default='', max_length=255)),
                ('payment_mode', models.CharField(blank=True, default='fixed', max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.tariff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_ids', models.TextField(blank=True, help_text="Vergul bilan ajratilgan chat ID'lar", null=True)),
                ('student_payments', models.BooleanField(default=False)),
                ('teacher_salaries', models.BooleanField(default=False)),
                ('expenses', models.BooleanField(default=False)),
                ('other_payments', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notification_setting', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
